"""empty message

Revision ID: 85560c1bafed
Revises: 
Create Date: 2017-04-03 19:15:54.730636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85560c1bafed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('long_urls',
    sa.Column('long_url_id', sa.Integer(), nullable=False),
    sa.Column('long_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('long_url_id')
    )
    op.create_index(op.f('ix_long_urls_long_url'), 'long_urls', ['long_url'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_table('visitors',
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('browser', sa.String(length=64), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('visitor_id')
    )
    op.create_index(op.f('ix_visitors_browser'), 'visitors', ['browser'], unique=False)
    op.create_index(op.f('ix_visitors_platform'), 'visitors', ['platform'], unique=False)
    op.create_table('short_urls',
    sa.Column('short_url_id', sa.Integer(), nullable=False),
    sa.Column('short_url', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('long_url_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['long_url_id'], ['long_urls.long_url_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('short_url_id'),
    sa.UniqueConstraint('short_url')
    )
    op.create_index(op.f('ix_short_urls_active'), 'short_urls', ['active'], unique=False)
    op.create_index(op.f('ix_short_urls_date_time'), 'short_urls', ['date_time'], unique=False)
    op.create_table('visits',
    sa.Column('visitor_id', sa.Integer(), nullable=True),
    sa.Column('short_url_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['short_url_id'], ['short_urls.short_url_id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.visitor_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_index(op.f('ix_short_urls_date_time'), table_name='short_urls')
    op.drop_index(op.f('ix_short_urls_active'), table_name='short_urls')
    op.drop_table('short_urls')
    op.drop_index(op.f('ix_visitors_platform'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_browser'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_long_urls_long_url'), table_name='long_urls')
    op.drop_table('long_urls')
    # ### end Alembic commands ###
