export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGOUT_USER = 'LOGOUT_USER'

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'

export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST'
export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA'

export const LOAD_POPULAR_URL_SUCCESS = 'LOAD_POPULAR_URL_SUCCESS'
export const LOAD_MOST_RECENT_URL_SUCCESS = 'LOAD_MOST_RECENT_URL_SUCCESS'
export const GET_ROUTE_TO_REDIRECT_FAILURE = 'GET_ROUTE_TO_REDIRECT_FAILURE'
export const GET_ROUTE_TO_REDIRECT_SUCCESS = 'GET_ROUTE_TO_REDIRECT_SUCCESS'
